version: '3'
services:
  app:
    build: .
    ports:
      - "8100:8100"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    depends_on:
      - redis
      - mongo
    restart: on-failure
    entrypoint: yarn run start:dev
    environment:
      MONGO_DSN: mongodb://mongo:27017/fortnight
      REDIS_DSN: redis://redis:6379/0
      PORT: 8100
      MONGOOSE_DEBUG: 1
  redis:
    image: redis:alpine
  mongo:
    image: mongo:3.4
    volumes:
      - mongodb:/data/db
    ports:
      - "8101:27017"
volumes:
  node_modules: {}
  mongodb: {}
